import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)

YELLOW_PIN = 23
RED_PIN = 24
GREEN_PIN = 25

GPIO.setup(YELLOW_PIN, GPIO.OUT)
GPIO.setup(RED_PIN, GPIO.OUT)
GPIO.setup(GREEN_PIN, GPIO.OUT)

GPIO.output(YELLOW_PIN, GPIO.HIGH)
GPIO.output(RED_PIN, GPIO.HIGH)
GPIO.output(GREEN_PIN, GPIO.HIGH)